"""Persist live Week 3 status and measured stage metrics; optionally watch detached."""
import argparse
from datetime import datetime, timezone
import fcntl
import json
import os
from pathlib import Path
import time

ROOT = Path(__file__).resolve().parent
STATE = ROOT / 'week3_runs'
BASELINE = ROOT / 'incremental_logs/sunrgbd_s5_object_memory_heightaware_1obj_sunrgbd40_s5_freqorder_20260908_151502'


def read_json(path):
    try:
        return json.loads(path.read_text())
    except (OSError, ValueError):
        return None


def collect():
    runs = []
    modes = ['pseudo_only', 'object_pseudo']
    modes += sorted(p.parent.name for p in STATE.glob('*/manifest.json')
                    if p.parent.name not in modes)
    for mode in modes:
        state = STATE / mode
        manifest = read_json(state / 'manifest.json') or {}
        stem = Path(manifest.get('work_dir_stem', ROOT / 'incremental_logs' / f'week3_{mode}_s201'))
        dirs = sorted(stem.parent.glob(stem.name + '_*'))
        run = dirs[-1] if dirs else None
        exit_file = state / 'exit_code'
        code = int(exit_file.read_text()) if exit_file.exists() else None
        trainer_file = state / 'trainer.pid'
        pid = int(trainer_file.read_text()) if trainer_file.exists() else None
        alive = False
        if pid is not None:
            try:
                cmdline = Path(f'/proc/{pid}/cmdline').read_bytes()
                alive = b'train_incremental_scene.py' in cmdline
            except OSError:
                pass
        status = ('completed' if code == 0 else 'failed') if code is not None else (
            'running' if alive else 'not observed alive; inspect host')
        invalid = read_json(state / 'invalid_ablation.json')
        if invalid:
            status = 'invalid ablation (stopped)'
        metrics = []
        pseudo = []
        if run:
            for stage in range(2, 6):
                data = read_json(run / 'memory_bank/scores' / f'stage_{stage}_metrics.json')
                if data and data.get('evaluated_at_stage') == stage:
                    # Per-class metrics prevent ambiguous old/new cohort scope.
                    classes = data.get('classes', [])
                    old = [c['AP_0.25'] for c in classes if c['model_idx'] < (stage - 1) * 8]
                    new = [c['AP_0.25'] for c in classes if (stage - 1) * 8 <= c['model_idx'] < stage * 8]
                    prior = read_json(BASELINE / 'memory_bank/scores' / f'stage_{stage}_metrics.json') or {}
                    metrics.append(dict(stage=stage, map25=data.get('mAP_0.25'),
                                        map50=data.get('mAP_0.50'),
                                        old_map25=sum(old)/len(old) if old else None,
                                        new_map25=sum(new)/len(new) if new else None,
                                        historical_object_no_pseudo=prior.get('mAP_0.25')))
            for path in sorted((run / 'pseudo_labels').glob('*stats.json')):
                data = read_json(path)
                if data:
                    pseudo.append(dict(path=str(path), stats=data))
        runs.append(dict(mode=mode, policy=manifest.get('mode', mode), seed=manifest.get('seed', 201),
                         status=status, invalid_ablation=invalid, exit_code=code, trainer_pid=pid,
                         supervisor_pid=manifest.get('supervisor_pid'), gpu=manifest.get('gpu'),
                         run_dir=str(run) if run else None, console=str(state/'console.log'),
                         metrics=metrics, pseudo=pseudo))
    report = dict(updated_at=datetime.now(timezone.utc).isoformat(), runs=runs)
    temp = STATE / 'status.json.tmp'
    temp.write_text(json.dumps(report, indent=2) + '\n')
    temp.replace(STATE / 'status.json')
    lines = ['# Week 3 — Live run status', '', f'Updated: {report["updated_at"]}', '',
             'Generated by `collect_week3_status.py`; protocol and reproducibility notes are in `EXPERIMENT_NOTES.md`.', '',
             '| Run | GPU | Status | Trainer PID |', '|---|---:|---|---:|']
    for run in runs:
        lines.append(f'| {run["mode"]} | {run["gpu"]} | {run["status"]} | {run["trainer_pid"]} |')
    lines += ['', '## Measured stage results', '',
              'Values are mAP fractions. Pending means no persisted stage metric yet. Invalid ablations are excluded.', '',
              '| Run | Stage | mAP@.25 | Old classes | New classes | Historical object/no-pseudo |',
              '|---|---:|---:|---:|---:|---:|']
    for run in runs:
        if run.get('invalid_ablation'):
            continue
        if not run['metrics']:
            lines.append(f'| {run["mode"]} | — | Pending | — | — | — |')
        for m in run['metrics']:
            def fmt(v):
                return f'{v:.4f}' if v is not None else '—'
            lines.append(f'| {run["mode"]} | {m["stage"]} | {fmt(m["map25"])} | '
                         f'{fmt(m["old_map25"])} | {fmt(m["new_map25"])} | '
                         f'{fmt(m["historical_object_no_pseudo"])} |')
    lines += ['', '## Artifacts', '']
    for run in runs:
        lines += [f'- {run["mode"]}: `{run["run_dir"]}`; console `{run["console"]}`.']
    lines += ['', 'Structured details, including pseudo-generation statistics: `week3_runs/status.json`.',
              'A completed process is not evidence of an improvement; compare final metrics and cohort retention.', '']
    temp_md = ROOT / 'WEEK_3_RUN_STATUS.md.tmp'
    temp_md.write_text('\n'.join(lines))
    temp_md.replace(ROOT / 'WEEK_3_RUN_STATUS.md')
    return bool(runs) and all(r['exit_code'] is not None for r in runs)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--watch', action='store_true')
    args = parser.parse_args()
    STATE.mkdir(exist_ok=True)
    with (STATE / 'status.lock').open('w') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        deadline = time.monotonic() + 24 * 3600
        while True:
            finished = collect()
            if not args.watch or finished:
                break
            if time.monotonic() >= deadline:
                print('Watcher timeout after 24h; trainers are untouched.', flush=True)
                break
            time.sleep(60)


if __name__ == '__main__':
    main()
